### ISSUE TITLE
如何在构建时添加 Sass 自定义函数

### ISSUE THREAD

**Issue by infinnie** [mycolorway/vest#5]
希望在 Sass 编译为 WXSS 之前执行自定义的 Sass 函数，在自己的项目之中可以如何配置呢。

**Comment by farthinker** [comment]
新发布的版本支持通过 `vest.config.js` 来配置 sass functions：
https://github.com/mycolorway/vest/commit/320b4de31c0bbef417343965f03da4f6319910eb
